server {
    listen 80;
    listen [::]:80;
    server_name yangjm.cn 47.104.154.48;
    root /var/www/yangjm.cn;
    index index.html;
    charset utf-8;
    server_tokens off;
    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;
    add_header Cache-Control "no-cache" always;

    location = / {
        expires -1;
        try_files /index.html =404;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ /\. {
        deny all;
    }

    location ^~ /.well-known/acme-challenge/ {
        default_type text/plain;
        try_files $uri =404;
    }
}
